### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shentao** [vuelidate/vuelidate#494]
# Roadmap

## Github Issues
- Investigate all issues, tag and label by type (in progress)
- Close none relevant or outdated ones (in progress)
- Note the major bugs and issues and tackle those first
- Outline biggest missing features of current version and see if workaround is possible (like error extractor)

## Documentation Related

- Transfer docs to Vuepress for easier contribution (in progress)
- Update docs to answer most common questions
- Add a whole section with recipes and examples
- Add a whole section explaining concepts and architecture

### v2

**Alpha released!**

- [x] Outline the new, most important features 
- [ ] Outline secondary features, that are not of most importance
- [x] Create official form handling, accompanying library for Vuelidate (https://github.com/vuelidate/formvuelatte)
- [x] Complete Rewrite
    - [ ] Using TypeScript (on hold)
    - [x] Simplify the codebase to make it easier to contribute code
    - [x] After initial attempts to rewrite it using Vue.observable, we decided to hold on the rewrite, due the fact that Vue 3.0 will most likely introduce the Advanced Reactivity API, which in turn would hugely simplify the internal implementation of Vuelidate. For example, it would allow us to stop creating Vue component instances on the fly to manage internal validation state. **Rewritten using the composition-api plugin**
- [ ] Docs (in progress)
- [ ] Migration guide (on hold)

### Major Changes in v2:

- [x] CHANGE: Extract validators to external package or leverage another package entirely
- [ ] NEW: Add first party error extraction logic with proper defaults. Should allow for scoped slots or instance method helpers
- [ ] NEW: Add better async validator support
- [ ] NEW: Allow validators to return extra data, not just booleans.
- [ ] NEW: Give parent components access to all child components validation results. This should allow for breaking up the validation schema and building nested forms with one central parent component that can decide on the actions.
- [x] IDEA: Remove the `$each` API
    - [ ] ~~Use map/reduce to validate arrays.~~ NEW: Introduce `every/some` helpers.

**Comment by ByScripts** [comment]
Nice to see the project is not dead and that a v2 is planned. But is it possible to release a new build with the latest fixes already merged ? There is a bug which make this lib unusable for us... It's a pity, because this bug is already fixed.

**Comment by CoolGoose** [comment]
Any way we can help with a temporary until v2 release with all of the new fix and tweaks ?

**Comment by blowsie** [comment]
I second the comments made above, were looking for feeback from the repo owners here;

 - Can we get a patch with the fixes?
 - How can the community help with v2.

**Comment by dobromir-hristov** [comment]
https://github.com/vuelidate/vuelidate/commits/next Next time, do your research.

**Comment by literakl** [comment]
Sorry, I was wrong that I trusted github. Have you looked at the link? 
Nevermind, what are the current plans?

**Comment by blowsie** [comment]
Im confused as to why this is closed.
Is v2 still in the making? Is there a new roadmap?

**Comment by shentao** [comment]
Hey! v2 is still in the making. It will stay that way up until Vue 3.0 is released due to the fact it is dedicated to Vue 3.0, with a compatibility layer using the composition-api plugin for Vue 2.x.

You can check out the progress on the `next` branch. It is already released as an alpha, though it’s rather buggy. 
We are currently working on solving some issues with the compatibility with the current Object-based API as well as exploring ideas on how to build context-aware validations. That is, components with validations reporting to ancestor components with validations so that you can split the validator declarations between different components, yet still have an easy way to access the results (with built-in messages). 

Here’s a presentation I made that touches heavily on what we have planned for Vuelidate (and also FormVueLatte). When it comes to an ETA – I plan on doing having most of those things done around mind February.

https://github.com/shentao/vue-3-for-library-authors/blob/master/vue-3-library-authors-january-update.pdf

**Comment by mikemathewson** [comment]
Is it possible to get a 0.7.7 release with the new bug fixes? Specifically, the email validation.
